### ISSUE TITLE
Issue installing package via pip3

### ISSUE THREAD

**Issue by MacqGit** [useblocks/sphinx-data-viewer#1]
First of all, thanks for the tremedous job.
I keep however struggling with the installation of this package on one of our Linux server.
pip3 install sphinx-data-viewer
"Collecting sphinx-data-viewer
  Using cached https://files.pythonhosted.org/packages/e1/3b/132e2c0517d5cd786308d9697877e922a89ef94950a319f884648dcc404a/sphinx-data-viewer-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    error in sphinx-data-viewer setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers."
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-fgl_s98l/sphinx-data-viewer/

This comes when installing " sphinxcontrib-needs".
I will install manually from .tar but would be nice if this could be fixed ;-)

**Comment by danwos** [comment]
Thanks for the bug report.

But I have some problems to reproduce this.
On my linux machine a "pip3 install sphinx-data-viewer" works and the package gets installed.
Tested with Python 3.9.5.

Also "sphinxcontrib-needs" is not a dependency of it.
It is only needed to build the project documentation and therefore mentioned only in ``docs/requirements.txt".

Honestly I have no idea what went wrong...

**Comment by danwos** [comment]
Maybe a `pip install --upgrade pip setuptools` helps, as the ``pyproject.toml`` is quite new to "pip" and your linux server may use an old version.

**Comment by MacqGit** [comment]
Hello @danwos, yes, you are right, in the meantime I ran:
python3 -m pip install --upgrade pip setuptools wheel

Apparently, the "setuptools"-"only" upgrade was not sufficient...

**Comment by danwos** [comment]
Nice that it was an easy one :)

I close the issue, but feel free to reopen, if I missed something.
