### ISSUE TITLE
Hardcoded "/" in paths

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinx-data-viewer#2]
Windows support is not given because of this bug.

Fix: ``extra_files = ['assets/jsonview.bundle.js', 'assets/jsonview_loader.js', 'assets/jsonview.bundle.css']``

Source report of this bug https://github.com/useblocks/sphinxcontrib-needs/issues/436

**Comment by danwos** [comment]
@PhilipPartsch: I merged a fix.
But before I create an official release, may I ask you to make a quick test on your windows machine?

Just install via
``pip install  pip install git+git://github.com/useblocks/sphinx-data-viewer.git``

Thanks!

**Comment by PhilipPartsch** [comment]
Hi, it worked for me.

**Comment by marcus-free** [comment]
Hi, it worked for me.

Windows 10

**Comment by danwos** [comment]
Looks good.
Will close and finally release tomorrow.
Thanks for all the help :+1:

**Comment by danwos** [comment]
Release done: https://pypi.org/project/sphinx-data-viewer/0.1.2/
